checks:
  php: true

filter:
  paths:
    - src/*

build:
  image: default-bionic

  environment:
    php:
      version: 8.2
      ini:
        xdebug.mode: coverage

  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run

    phpunit:
      dependencies:
        override:
          - composer self-update
          - composer update --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi

      tests:
        override:
          - command: composer run tests
            on_node: 1
            coverage:
              file: var/report/coverage.xml
              format: php-clover