checks:
  php: true

filter:
  paths:
    - src/*
    - tests/*

build:
  environment:
    php:
      version: 8.2
  tests:
    override:
      command: "php -v"
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run