checks:
  php: true

filter:
  paths:
    - src/*
    - tests/*

build:
  environment:
    php:
      version: 8.2

  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run