name: Code Verification

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  coding-guidelines:
    name: Coding Guidelines

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: composer update --prefer-dist --no-progress

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Run codesniffer
        run: composer run phpcs

      - name: Run mess detector
        run: composer run phpmd

      - name: Run phpstan
        run: composer run phpstan

  tests:
    name: Unit and Integration Tests

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version:
          - "8.2"
          - "8.3"

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP with Xdebug
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php-version }}"
          coverage: xdebug

      - name: Install dependencies
        run: composer update --prefer-dist --no-progress

      - name: Run test suite
        run: |
          export API_KEY=${{secrets.API_KEY}}
          composer run tests

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3