name: Code Verification

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  coding-guidelines:
    name: Coding Guidelines

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: composer update --prefer-dist --no-progress

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Run codesniffer
        run: composer run phpcs

      - name: Run mess detector
        run: composer run phpmd

  tests:
    name: Unit and Integration Tests

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: composer update --prefer-dist --no-progress

      - name: Run test suite
        run:
          export API_KEY=${{secrets.API_KEY}}
          composer run tests
